package org.ecsoya.iec60870.asdu.ie.value;

public enum FileServerState {
	UNSELECTED_IDLE,
	WAITING_FOR_FILE_CALL,
	WAITING_FOR_SECTION_CALL,
	TRANSMIT_SECTION,
	WAITING_FOR_SECTION_ACK,
	WAITING_FOR_FILE_ACK,
	SEND_ABORT,
	TRANSFER_COMPLETED
}